export enum Actions {
    ADD_BOOK = 'ADD_BOOK',
    REMOVE_BOOK = 'REMOVE_BOOK',
    TOGGLE_READ_STATUS = 'TOGGLE_READ_STATUS',
    TOGGLE_SEND_NOTIFICATION = 'TOGGLE_SEND_NOTIFICATION',
    LOAD_BOOKS = 'LOAD_BOOKS',
    SEARCH_BOOK = 'SEARCH_BOOK',
    PRIORITY_FILTER = 'PRIORITY_FILTER',

    LOAD_CATEGORIES = 'LOAD_CATEGORIES',
    ADD_CATEGORY = 'ADD_CATEGORY',

    ADD_EDITED_BOOK = 'ADD_EDIT_BOOK',
    REMOVE_EDITED_BOOK = 'REMOVE_EDITED_BOOK',
    LOAD_USER = 'LOAD_USER',
    REMOVE_USER = 'REMOVE_USER'
}
